import express from "express";
import PDFDocument from "pdfkit";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();

// Hardcoded services
const services = [
  {
    id: 1,
    slug: "birth-certificate",
    name: "Birth Certificate",
    formFields: ["Full Name", "Date of Birth", "Place of Birth", "Father's Name", "Mother's Name"]
  },
  {
    id: 2,
    slug: "marriage-certificate",
    name: "Marriage Certificate",
    formFields: ["Full Name", "Spouse Name", "Marriage Date", "Place of Marriage", "Father's Name", "Mother's Name"]
  },
  {
    id: 3,
    slug: "income-certificate",
    name: "Income Certificate",
    formFields: ["Full Name", "Father's Name", "Annual Income"]
  },
  {
    id: 4,
    slug: "caste-certificate",
    name: "Caste Certificate",
    formFields: ["Full Name", "Father's Name", "Caste", "District"]
  },
  {
    id: 5,
    slug: "water-bill-payment",
    name: "Water Bill Payment",
    formFields: ["Consumer Number", "Billing Month", "Amount"]
  },
  {
    id: 6,
    slug: "property-tax-payment",
    name: "Property Tax Payment",
    formFields: ["Property ID", "Owner Name", "Amount"]
  },
];

// GET all services
router.get("/", (req, res) => {
  res.json(services);
});

// GET service by slug
router.get("/:slug", (req, res) => {
  const service = services.find(s => s.slug === req.params.slug);
  if (service) res.json(service);
  else res.status(404).json({ message: "Service not found" });
});

// POST route to generate PDF
router.post("/certificate/:serviceId", (req, res) => {
  const { serviceId } = req.params;
  const formData = req.body;

  const doc = new PDFDocument({ margin: 50 });

  // Set response headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${serviceId.replace("-", "_")}.pdf`
  );

  doc.pipe(res);

  // Logo
  const logoPath = path.join(__dirname, "../public/E-gram.jpg");
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, 50, 40, { width: 80 });
  } else {
    console.warn("Logo not found at:", logoPath);
  }

  doc.moveDown(4);

  // Title
  doc.fontSize(22).fillColor("#2E8B57").text("E-Gram Panchayat Certificate", {
    align: "center",
  });
  doc
    .fontSize(18)
    .fillColor("black")
    .text(
      `Service: ${
        serviceId.charAt(0).toUpperCase() + serviceId.slice(1).replace("-", " ")
      }`,
      { align: "center" }
    );

  doc.moveDown(2);

  // Form data
  Object.entries(formData).forEach(([key, value]) => {
    doc.fontSize(14).text(`${key}: ${value}`, { lineGap: 4 });
  });

  doc.moveDown(3);
  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by E-Gram Panchayat System", { align: "center" });

  doc.end();
});

export default router;
