import express from "express";
import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();

// Hardcoded services
let services = [
  {
    id: 1,
    slug: "birth-certificate",
    name: "Birth Certificate",
    description: "Apply for new birth certificates online",
    category: "Certificates",
    formFields: ["Full Name", "Date of Birth", "Place of Birth", "Father's Name", "Mother's Name"]
  },
  {
    id: 2,
    slug: "marriage-certificate",
    name: "Marriage Certificate",
    description: "Apply for marriage certificate",
    category: "Certificates",
    formFields: ["Full Name", "Spouse Name", "Marriage Date", "Place of Marriage", "Father's Name", "Mother's Name"]
  },
  {
    id: 3,
    slug: "income-certificate",
    name: "Income Certificate",
    description: "Apply for income certificate",
    category: "Certificates",
    formFields: ["Full Name", "Father's Name", "Annual Income"]
  },
  {
    id: 4,
    slug: "caste-certificate",
    name: "Caste Certificate",
    description: "Apply for caste certificate",
    category: "Certificates",
    formFields: ["Full Name", "Father's Name", "Caste", "District"]
  },
  {
    id: 5,
    slug: "water-bill-payment",
    name: "Water Bill Payment",
    description: "Pay your water supply bills",
    category: "Bills",
    formFields: ["Consumer Number", "Billing Month", "Amount"]
  },
  {
    id: 6,
    slug: "property-tax-payment",
    name: "Property Tax Payment",
    description: "Pay your property tax digitally",
    category: "Taxes",
    formFields: ["Property ID", "Owner Name", "Amount"]
  },
];

// GET all services
router.get("/", (req, res) => {
  res.json(services);
});

// GET service by slug
router.get("/:slug", (req, res) => {
  const service = services.find(s => s.slug === req.params.slug);
  if (service) res.json(service);
  else res.status(404).json({ message: "Service not found" });
});

// POST route to generate PDF
router.post("/certificate/:serviceId", (req, res) => {
  const { serviceId } = req.params;
  const formData = req.body;

  console.log("Received form data:", formData); // check data

  const doc = new PDFDocument({ margin: 50 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=${serviceId}.pdf`);
  doc.pipe(res);

  // Add logo
  const logoPath = path.join(__dirname, "../public", "E-gram.jpg");
  try {
    doc.image(logoPath, 50, 30, { width: 80 });
  } catch (err) {
    console.error("Logo not found:", err.message);
  }

  doc.moveDown(2);

  // Title
  doc.fontSize(22).fillColor("#2E8B57").text("E-Gram Panchayat", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(18).fillColor("black").text(`Service: ${serviceId.replace("-", " ").toUpperCase()}`, { align: "center" });

  doc.moveDown(2);

  // Form data
  Object.entries(formData).forEach(([key, value]) => {
    doc.fontSize(14).text(`${key}: ${value}`, { lineGap: 4 });
  });

  doc.moveDown(3);
  doc.fontSize(10).fillColor("gray").text("Generated by E-Gram Panchayat System", { align: "center" });

  doc.end();
});

export default router;
